server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hr
    username: root
    password: jayanti@2021
  jpa:
     open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2
    
